version: '3.8'

services:
  imagedgd:
    build: .
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./figures:/app/figures
      - ./models:/app/models
      - ./mlruns:/app/mlruns
      - ./optuna_studies:/app/optuna_studies
    ports:
      - "5000:5000"  # MLflow UI
      - "8080:8080"  # Optuna dashboard
    environment:
      - PYTHONPATH=/app/src
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    
  mlflow:
    build: .
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri file:/app/mlruns --default-artifact-root /app/mlruns
    volumes:
      - ./mlruns:/app/mlruns
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
      
  jupyter:
    build: .
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app/src
