random_seed: 42
experiment_name: ImageDGD_Default
description: Default ImageDGD training configuration
data:
  dataset: FashionMNIST
  data_dir: ./data
  batch_size: 128
  num_workers: 4
  pin_memory: true
  use_subset: false
  subset_fraction: 1.0
  normalize: true
  dataset_name: FashionMNIST
  root_dir: /home/asp/Downloads/HeaDS/ImageDGD/data
  download: true
  shuffle_train: true
  shuffle_test: false
  transforms:
    train:
    - ToTensor
    - Normalize
    test:
    - ToTensor
    - Normalize
  class_names:
  - T-shirt/top
  - Trouser
  - Pullover
  - Dress
  - Coat
  - Sandal
  - Shirt
  - Sneaker
  - Bag
  - Ankle boot
model:
  representation:
    n_features: 2
    distribution: uniform_ball
    dist_params:
      radius: 1.0
  decoder:
    hidden_dims:
    - 128
    - 64
    - 32
    output_channels: 1
    output_size:
    - 28
    - 28
    init_size:
    - 4
    - 4
    kernel_size: 3
    stride: 2
    padding: 1
    output_padding: 1
    bias: true
    normalization: batch
    activation: leaky_relu
    final_activation: sigmoid
    dropout_rate: 0.0
    upsampling_mode: transpose
    use_spectral_norm: false
    use_self_attention: false
    attention_resolution: 32
  gmm:
    n_components: 20
    covariance_type: full
    init_params: kmeans
    verbose: false
    max_iter: 1000
    tol: 0.001
    n_init: 1
    warm_start: true
training:
  epochs: 200
  device: auto
  first_epoch_gmm: 50
  refit_gmm_interval: 50
  lambda_gmm: 1.0
  optimizer:
    decoder:
      type: AdamW
      lr: 0.001
      weight_decay: 0.01
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
    representation:
      type: AdamW
      lr: 0.01
      weight_decay: 0.0
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
  logging:
    log_interval: 1
    plot_interval: 50
    save_figures: true
    figure_format: png
    dpi: 150
clearml:
  enabled: true
  project_name: ImageDGD
  task_name: Default_Training
  tags:
  - default
  - production
