random_seed: 42
experiment_name: ImageDGD_Minimal_Test
description: Minimal configuration for fast testing and debugging
data:
  dataset: FashionMNIST
  data_dir: /home/asp/Downloads/HeaDS/ImageDGD/data
  batch_size: 128
  num_workers: 2
  pin_memory: true
  use_subset: true
  subset_fraction: 0.05
  normalize: true
  root_dir: /home/asp/Downloads/HeaDS/ImageDGD/data
  dataset_name: FashionMNIST
  download: true
  transforms:
    train:
    - ToTensor
    - Normalize
    test:
    - ToTensor
    - Normalize
  shuffle_train: true
  shuffle_test: false
  class_names:
  - T-shirt/top
  - Trouser
  - Pullover
  - Dress
  - Coat
  - Sandal
  - Shirt
  - Sneaker
  - Bag
  - Ankle boot
model:
  representation:
    n_features: 4
    distribution: uniform
    radius: 1.0
  decoder:
    hidden_dims:
    - 32
    - 16
    output_channels: 1
    output_size:
    - 28
    - 28
    init_size:
    - 7
    - 7
    kernel_size: 3
    stride: 2
    padding: 1
    output_padding: 1
    bias: true
    normalization: none
    use_batch_norm: false
    activation: relu
    final_activation: sigmoid
    dropout_rate: 0.0
    upsampling_mode: nearest
    use_spectral_norm: false
    use_self_attention: false
  gmm:
    n_components: 2
    covariance_type: diag
    init_params: random
    verbose: false
    max_iter: 50
    tol: 0.01
    n_init: 1
    warm_start: true
training:
  epochs: 10
  device: auto
  first_epoch_gmm: 5
  refit_gmm_interval: 10
  lambda_gmm: 0.1
  optimizer:
    decoder:
      type: Adam
      lr: 0.01
      weight_decay: 0.0
    representation:
      type: Adam
      lr: 0.1
      weight_decay: 0.0
  logging:
    log_interval: 5
    plot_interval: 5
    save_figures: false
    figure_format: png
    dpi: 72
clearml:
  enabled: false
  project_name: ImageDGD_Test
  task_name: Minimal_Test
  tags:
  - minimal
  - test
  - debug
hardware:
  mixed_precision: false
  compile_model: false
  benchmark_cudnn: false
