# @package _global_

# Optuna optimization configuration
optimization:
  enabled: true
  study_name: "dgd_optimization"
  storage: "sqlite:///optuna_studies/dgd_study.db"
  direction: "minimize"
  n_trials: 100
  timeout: null  # seconds, null for no timeout
  
  # Pruning
  pruner:
    type: "MedianPruner"
    n_startup_trials: 5
    n_warmup_steps: 30
    interval_steps: 10
    
  # Sampler
  sampler:
    type: "TPESampler"
    n_startup_trials: 10
    
  # Objective metric
  objective:
    metric: "val_total_loss"
    direction: "minimize"
    
  # Parameter search space
  parameters:
    # Model parameters
    model.representation.n_features:
      type: "int"
      low: 3
      high: 10
      
    model.representation.radius:
      type: "float"
      low: 0.01
      high: 1.0
      log: true
      
    model.decoder.hidden_dims_0:
      type: "categorical"
      choices: [64, 128, 256, 512]
      
    model.decoder.hidden_dims_1:
      type: "categorical" 
      choices: [32, 64, 128, 256]
      
    model.decoder.dropout_rate:
      type: "float"
      low: 0.0
      high: 0.5
      
    model.gmm.n_components:
      type: "int"
      low: 5
      high: 50
      
    # Training parameters
    training.lambda_gmm:
      type: "float"
      low: 0.1
      high: 10.0
      log: true
      
    training.optimizer.decoder.lr:
      type: "float"
      low: 1e-5
      high: 1e-2
      log: true
      
    training.optimizer.representation.lr:
      type: "float"
      low: 1e-4
      high: 1e-1
      log: true
