# @package _global_

# Model configuration
model:
  name: "dgd_conv"
  
  # Representation layer settings
  representation:
    n_features: 5
    distribution: "uniform_ball"
    radius: 0.1
    
  # Decoder settings  
  decoder:
    type: "conv"
    hidden_dims: [128, 64, 32]
    output_channels: 1
    output_size: [28, 28]
    init_size: [7, 7]
    use_batch_norm: true
    activation: "leaky_relu"
    final_activation: "sigmoid"
    dropout_rate: 0.1
    
  # GMM settings
  gmm:
    n_components: 20
    covariance_type: "diag"
    init_params: "kmeans"
    max_iter: 1000
    tol: 1e-4
    warm_start: true
    verbose: false
    n_init: 1
