# @package _global_

# Model configuration optimized for weak GPUs
model:
  # Representation layer (smaller)
  representation:
    n_features: 3  # Reduced latent dimension
    distribution: "uniform_ball"
    radius: 0.1
    
  # Decoder configuration (smaller)
  decoder:
    hidden_dims: [64, 32]  # Smaller hidden dimensions
    output_channels: 1
    output_size: [28, 28]
    init_size: [7, 7]
    activation: "leaky_relu"
    final_activation: "sigmoid"
    use_batch_norm: true
    dropout_rate: 0.1
    
  # GMM configuration (fewer components)
  gmm:
    n_components: 10  # Reduced number of components
    covariance_type: "diag"
    init_params: "kmeans"
    max_iter: 500  # Reduced iterations
    tol: 1e-4
    n_init: 1
    warm_start: true
    verbose: false
